# This is a basic workflow to help you get started with Actions

name: main-web

on:
    pull_request:
        branches:
            - "**"

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    Checkstyle:
        runs-on: ubuntu-latest
        name: Checkstyle job
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Run check style
                uses: asaasdev/checkstyle-action@v1
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    reporter: 'github-pr-review'
                    fail_on_error: true
                    filter_mode: file
                    level: error
                    configuration_file: /home/runner/work/ume-main-web/ume-main-web/checkstyle_config.xml
    Build_test:
        runs-on: ubuntu-latest
        name: Build and test
        steps:
            -   name: Checkout branch
                uses: actions/checkout@v3

            -   name: Set up JDK 11
                uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'adopt'

            -   name: Cache maven packages
                uses: actions/cache@v3
                with:
                    path: ~/.m2
                    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                    restore-keys: ${{ runner.os }}-m2

            -   name: Build and Run Tests
                run: mvn test -B
            -   name: Publish Test Report
                uses: mikepenz/action-junit-report@v3
                if: always() # always run even if the previous step fails
                with:
                    report_paths: '**/build/test-results/test/TEST-*.xml'
